### ISSUE TITLE
Initialize a repo with specified file(s)

### ISSUE THREAD

**Issue by jwsloan** [probot/ideas#87]
Currently you can initialize a project with a README file. It would be handy to initialize it with one or more probot configs in the `.github` folder. Maybe taking whatever is in the `.github` repo, if it exists. They could always be deleted if unwanted. 

I'm thinking of this specifically for the `Settings` app so that we can ensure Protected Branches is turned on as we want it with every new repo.

**Comment by Jme7** [comment]
Well, there is a workaround. You can have a template containing those and use that as a template for your repos. That's the best I've got.

**Comment by gr2m** [comment]
apps are looking for the `.github` folder in the `.github` repository by default, so no need to copy them over, unless you want to override them

**Comment by travi** [comment]
based on the date of this being opened, i think that was before either template repositories were a github feature or probot-config being built directly into probot for reading config from the `.github` repo. i use the protected branches functionality of the settings app in my organization accounts and personal account successfully, so i would say this request has since been satisfied

**Comment by gr2m** [comment]
good point, agree :)
